### ISSUE TITLE
Controlling baskit throught telegram bots [suggestion]

### ISSUE THREAD

**Issue by llemonS** [SteveMcGrath/baskit#16]
I would like to suggest this idea to baskit project. To be honest, I've already made some scripts on this concept, but as I am an "python newbie" I'm a bit ashamed to pull my code.
![minecraftzz](https://cloud.githubusercontent.com/assets/10836949/21641014/20f2c6ec-d260-11e6-8e3c-da2f72a51346.png)

**Comment by SteveMcGrath** [comment]
well you can always slap it into a diff branch.  never used telegram, so id be interested to see how you did it

**Comment by SteveMcGrath** [comment]
note https://github.com/SteveMcGrath/baskit/pull/18
